- name: IP Configuration
  hosts: routers
  gather_facts: no

  tasks:

    - name: Configure R1 interface
      when: inventory_hostname == "R1"
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet1
          - ip address 10.0.12.1 255.255.255.252
          - no shutdown

    - name: Configure R2 interface (SSH network)
      when: inventory_hostname == "R2"
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet1
          - ip address 192.168.56.102 255.255.255.0
          - no shutdown

    - name: Add R2 simulated network (loopback)
      when: inventory_hostname == "R2"
      cisco.ios.ios_config:
        lines:
          - interface Loopback0
          - ip address 10.0.12.2 255.255.255.252