- import_playbook: playbooks/device_info.yml
- import_playbook: playbooks/static_route.yml
- import_playbook: playbooks/banner.yml
- import_playbook: playbooks/base_setup.yml
- import_playbook: playbooks/ip_config.yml

