- name: Network Automation Main Controller
  hosts: routers
  gather_facts: no

  tasks:

    - name: Run device info collection
      import_playbook: playbook/device_info.yml

    - name: Run static route config
      import_playbook: playbook/static_route.yml
